version: '3.8'

services:
  # docker-compose.yml
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=proxy_user
      - RABBITMQ_DEFAULT_PASS=secure_password
      - RABBITMQ_DEFAULT_VHOST=proxy_system
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]

  tcp_proxy:
    build:
      context: .
      dockerfile: Dockerfile.tcp_proxy
    ports:
      - "8880:8880"
    networks:
      - mynetwork
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8010:8010"
    networks:
      - mynetwork
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  health_check:
    build:
      context: .
      dockerfile: Dockerfile.health_check
    networks:
      - mynetwork
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  process_queue:
    build:
      context: .
      dockerfile: Dockerfile.process_queue
    networks:
      - mynetwork
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork: